# Generated by Django 5.2.11 on 2026-04-16 16:07

import core.utils.upload_images
from django.db import migrations, models

import users.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='photo',
            field=models.ImageField(default=1, upload_to=users.utils.upload_address),
            preserve_default=False,
        ),
    ]
