# Generated by Django 5.2.11 on 2026-02-20 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='recipient_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
