# Generated by Django 5.2.11 on 2026-04-17 14:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_address_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
