# Generated by Django 5.2.11 on 2026-04-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_address_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='photo',
            field=models.ImageField(upload_to='upload_address'),
        ),
    ]
