# Generated by Django 5.2.11 on 2026-04-19 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_address_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='address',
            name='uid',
        ),
    ]
